#!/bin/sh
[[ -f ~/.config/X11/xresources ]] && xrdb -merge -I$HOME ~/.config/X11/xresources
#nitrogen --restore &
#xcompmgr &
#megasync &
#udiskie &
#dunst &
#fcitx -d &
#clipmenud &
#sudo corectrl &
#st -e etc_mine &
#xflux -l -22.0033 -g -47.8879 &
setxkbmap -layout us -variant altgr-intl -option nodeadkeys
[[ -f ~/.config/X11/xmodmap ]] && xmodmap ~/.config/X11/xmodmap
[ -f /etc/xprofile ] && . /etc/xprofile
export XDG_SESSION_TYPE=x11
exec dwm
